# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

#require(File.join(File.dirname(__FILE__), 'config', 'boot'))

RAILS_ROOT = File.dirname(__FILE__)

require 'rake'
require 'echoe'

Echoe.new('ruby-django-run', '0.1.0') do |p|
  p.description    = "A gem to execute django code inside a ruby code"
  p.url            = "http://github.com/timotta/ruby-django-run"
  p.author         = "Tiago Albineli Motta"
  p.email          = "timotta@gmail.com"
  p.ignore_pattern = ["spec/*", "tmp/*"]
  p.development_dependencies = []
end

